sudo: true
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  matrix:
    - ACE=1
  global:
    - CURPATH=$(pwd)
    - ACEDIR=$HOME/Tools
    - ACE_ROOT=$ACEDIR/ACE_TAO/ACE
    - TAO_ROOT=$ACEDIR/ACE_TAO/TAO
    - MPC_ROOT=$ACEDIR/ACE_TAO/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7

before_install:
  - mkdir -p $ACEDIR
  - cd $ACEDIR
  - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.tar.gz
  - tar zxvf ACE-6.4.0.tar.gz
  - ls ./

before_script:
  - export
  - ls $ACE_ROOT/lib
script:
  - echo -e "hello world!"
  - echo -e $ACE_ROOT
  - echo -e $CURPATH