sudo: true
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  matrix:
    - ACE=1
  global:
    - CURPATH=$(pwd)
    - ACEDIR=$HOME/Tools
    - ACE_ROOT=$ACEDIR/ACE_TAO/ACE_wrappers
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7

before_install:
  - mkdir -p $ACEDIR
  - cd $ACEDIR
  - wget http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.tar.gz
  - tar zxvf ACE-6.4.0.tar.gz
  - ls ./

before_script:
  - export
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo -e "#define ACE_HAS_EVENT_POLL" >> $ACE_ROOT/ace/config.h; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      else
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      fi
    fi
  - ls $ACE_ROOT/lib/
script:
  - echo -e "hello world!"
  - echo -e $ACE_ROOT
  - echo -e $CURPATH