language: cpp
compiler:
    - g++
env:
    - ACE_ROOT=/usr/local/ACE_wrappers
script:
    #- $CXX main.cpp -o cpp_ci_test.o
    #- ./cpp_ci_test.o
    - echo -e "hello world!"
    - echo -e $ACE_ROOT
    pwd