language: c++

sudo: required

compiler:
  - gcc
os:
  - linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "d14aceb3ccd480c6f7a37d89595b3b1a11d65ac4"

addons:
  coverity_scan:
    project:
      name: "liuchao412/HelloACE"
      description: "Build submitted via Travis CI"
    notification_email: liuchao412@foxmail.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

  #Codecov
  - sudo pip install codecov
  - chmod +x .get_code_cov.sh

  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
 
  #Codecov
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  - mkdir bin
  #Compile without optimization and with coverage
  - make test
  #Run the program
  - cd bin/
  - ./application test
  - cd ..
  #Codecov
  - ./.get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
